config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :targets
  get 'pages/index'
  root 'pages#index'
  get 'users/:id' => 'users#show', as: :user
  get 'users', to: 'users#index', as: :users
  get 'personal', to: 'targets#personal', as: :personal
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :target
	belongs_to :user
end

app/models/target.rb
class Target < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :targets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

      if @comment.save
        redirect_to target_path(@comment.target_id), notice: 'Comment was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:message, :target_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	
  end

  def contact

  end

  def about

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :about)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :about)
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all.order('targets.created_at DESC')
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
    @comment = Comment.new
  end

  def personal

  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  # POST /targets.json
  def create
    #@target = Target.new(target_params)
    @target = current_user.targets.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: 'Target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_params
      params.require(:target).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
	  @user = User.find_by_id(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Target</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.message %></td>
        <td><%= comment.target_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @comment.message %>
</p>

<p>
  <strong>Target:</strong>
  <%= @comment.target_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


  </head>

  <body>


  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Target Reacher</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav" style="z-index: 999;">
        <% if user_signed_in? %> 
          <li class="flow-text" style="color: black; margin: auto; padding-left: 32px;">Hello, <%= current_user.name %></li>
          <div class="divider"></div>
          <li><a href="/personal">My Targets</a></li>
          <li><a href="/users">All Members</a></li>
          <li><a href="/targets">Hot targets</a></li>
          <div class="divider"></div>
          <li><a href="/about">About Us</a></li>
          <li><a href="/contact">Contact</a></li>
          <div class="divider"></div>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><a href="/users/sign_in">Log in</a></li>
          <li><a href="/users/sign_up">Registration</a></li>
          <div class="divider"></div>
          <li><a href="/about">About Us</a></li>
          <li><a href="/contact">Contact</a></li>
          <% end %>

      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div class="section no-pad-bot" id="index-banner">
    <div class="container">

      <div class="row center">

          <%= yield %>
      </div>

    </div>
  </div>





   
  <script>
  (function($){
  $(function(){

    $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space

</script>
  </body>
</html>

app/views/pages/about.html.erb
<h3>About us</h3>
<p class="flow-text">This application was created as practical part of the thesis in the Akademia Finansow i Biznesu Vistula by <strong>Iulian Sardar</strong></p>
<p class="flow-text">Author is student of the Computer Science faculty</p>

app/views/pages/contact.html.erb
<h3>Contact</h3>
<p class="flow-text">For any questions and suggestions</p>
<p class="flow-text">Feel free to contact with me</p>
<p class="flow-text">by e-mail: <b>sardarmma@gmail.com</b></p>

app/views/pages/index.html.erb
<p class="flow-text">Welcome to the target reacher application</p>
<p class="flow-text">Here you could set up your goals and observe targets of another members</p>
<p class="flow-text">Also, you have an opportunity to support other people on their path to success</p>
<br><br><br><br><br>

app/views/targets/_form.html.erb
<%= form_for(target) do |f| %>

  <div class="field">
    <%= f.label :title, class: 'flow-text' %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description, class: 'flow-text' %>
    <%= f.text_area :description, class: 'materialize-textarea' %>
  </div>


  <div class="actions">
    <%= f.submit nil, class: 'waves-effect waves-light btn' %>
  </div>
<% end %>

app/views/targets/edit.html.erb
<h1>Editing Target</h1>

<%= render 'form', target: @target %>

<br>
<%= link_to 'Back', personal_path, class: 'btn' %>

app/views/targets/index.html.erb
<h1>Targets</h1>

<ul class="collection">
     <% @targets.each do |target| %>
    <li class="collection-item">
     <span class="title"><strong>Target:</strong> <%= target.title %></span><br>
     <span><strong>Member:</strong> <%= link_to target.user.name, target.user %></span>
      <p><strong>Description:</strong> <%= target.description %></p>
      <p>
        <%= link_to 'Visit', target, class: 'btn' %>
      </p>

    </li>
        <% end %>
  </ul>





<%= link_to 'New Target', new_target_path, class: 'btn' %>

app/views/targets/new.html.erb
<h1>New Target</h1>

<%= render 'form', target: @target %>

app/views/targets/personal.html.erb
<h3>My Targets</h3>
 <ul class="collection">
     <% current_user.targets.each do |target| %>
    <li class="collection-item">
     <span class="title"><strong>Target:</strong> <%= target.title %></span>
      <p><strong>Description:</strong> <%= target.description %></p>
      <p>
        <%= link_to 'Visit', target, class: 'btn' %> <%= link_to 'Edit', edit_target_path(target), class: 'btn' %> <%= link_to 'Delete', target, method: :delete, class: 'btn', data: { confirm: 'Are you sure?' } %>
      </p>
    </li>
        <% end %>
  </ul>

<br>
<%= link_to 'New Target', new_target_path, class: 'btn' %>

app/views/targets/show.html.erb
  <div class="row">
      <div class="col s12 flow-text blue lighten-2"><h4>Target</h4> <h5><%= @target.title %></h5></div>
      <div class="col s12 flow-text"><h5>Description</h5> <%= @target.description %></div>
      <div class="col s12 flow-text"><strong>Targeted by </strong><%= link_to @target.user.name, @target.user %></div>
   </div>


<div class="row">
<div class="col s12"><h5>Comments</h5></div>

<% @target.comments.each do |comment| %>
 <ul class="collection">
    <li class="collection-item">
     <span class="title"><%= comment.user.name %></span>
      <p><%= comment.message %></p>
    </li>
  </ul>
<% end %>
</div>




<p>
  <h5>New comment</h5>
       <%= form_for [@comment] do |f| %>
           <div class="form-group">
             <%= f.text_area :message, class: "materialize-textarea" %>
           </div>
           <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
           <%= f.text_field :target_id, value: @target.id, type: "hidden" %>
           <div class="form-group text-center">
             <%= f.submit "POST", class: "btn" %>
           </div>
      <% end %>
</p>

<%= link_to 'Back', @target.user, class: "btn"  %>

app/views/users/index.html.erb
<h3>List of people</h3>
 <ul class="collection">
     <% @users.each do |user| %>
    <li class="collection-item">
     <span class="title"><strong>Name:</strong> <%= user.name %></span>
      <p><strong>About:</strong> <%= user.about %></p>
      <p><strong>Amount of targets: </strong> <%= user.targets.count %></p>
      <p>
        <%= link_to 'Visit', user, class: 'btn' %>
      </p>
    </li>
        <% end %>
  </ul>

app/views/users/show.html.erb
<h3><%= @user.name %>'s Targets</h3>
 <ul class="collection">
     <% @user.targets.each do |target| %>
    <li class="collection-item">
     <span class="title"><strong>Target:</strong> <%= target.title %></span>
      <p><strong>Description:</strong> <%= target.description %></p>
      <p>
        <%= link_to 'Visit', target, class: 'btn' %>
      </p>
    </li>
        <% end %>
  </ul>

<br>

<p><%= link_to 'Return to people', users_path, class: 'btn' %> <%= link_to 'Return to targets', targets_path, class: 'btn' %></p>